export default {
  "_v": "17.1",
  "_type": "category",
  "categories": [
    {
      "_type": "category",
      "description": "All Arahi 2 Shoes.",
      "id": "arahi2",
      "name": "Arahi 2",
      "parent_category_id": "root"
          },
    {
      "_type": "category",
      "id": "clayton-2",
      "name": "Clayton 2",
      "parent_category_id": "root",
      "c_catShowGender": true,
      "c_enableCompare": false,
      "c_hideInDSS": false,
      "c_isExcludeTranslate": false,
      "c_isMobileOnlyInMobileNav": false,
      "c_pageDisableInfinite": false,
      "c_removeHokaRideFinder": false,
      "c_showGender": false,
      "c_showInEndlessAisleMenu": false,
      "c_showInMenu": false,
      "c_showInSidebarMenu": false,
      "c_siteSiteMapRemove": false
          },
    {
      "_type": "category",
      "id": "clifton",
      "name": "Clifton",
      "parent_category_id": "root",
      "c_catShowGender": true,
      "c_enableCompare": false,
      "c_hideInDSS": false,
      "c_isMobileOnlyInMobileNav": false,
      "c_pageDisableInfinite": false,
      "c_removeHokaRideFinder": false,
      "c_showGender": true,
      "c_showInEndlessAisleMenu": false,
      "c_showInMenu": false,
      "c_showInSidebarMenu": false,
      "c_siteSiteMapRemove": false
          },
    {
      "_type": "category",
      "id": "clifton-4",
      "name": "Clifton 4",
      "parent_category_id": "root",
      "c_catShowGender": true,
      "c_enableCompare": false,
      "c_hideInDSS": false,
      "c_isMobileOnlyInMobileNav": false,
      "c_pageDisableInfinite": false,
      "c_removeHokaRideFinder": false,
      "c_showGender": true,
      "c_showInEndlessAisleMenu": false,
      "c_showInMenu": false,
      "c_showInSidebarMenu": false,
      "c_siteSiteMapRemove": false
          },
    {
      "_type": "category",
      "id": "compare-running-shoes",
      "name": "Shoe Finder",
      "page_description": "Use this page to compare HOKA ONE ONE® running shoes exclusively on HOKAONEONE.com. Enjoy free shipping and returns on all orders!",
      "page_title": "HOKA ONE ONE® | Compare HOKA Running Shoes",
      "parent_category_id": "root",
      "c_catShowGender": true,
      "c_enableCompare": false,
      "c_hreflangindex": "26",
      "c_isExcludeTranslate": false,
      "c_isMobileOnlyInMobileNav": false,
      "c_showGender": true,
      "c_showInMenu": false,
      "c_showInSidebarMenu": false,
      "c_siteSiteMapRemove": false
          },
    {
      "_type": "category",
      "id": "gift-guide",
      "name": "Gift Guide",
      "page_description": "Shop the HOKA ONE ONE® gift guide to share your favorite running shoes with the men & women in your life, including the new Clifton 3!",
      "page_title": "HOKA ONE ONE® | Shop the HOKA Gift Guide",
      "parent_category_id": "root",
      "c_catShowGender": true,
      "c_enableCompare": false,
      "c_hreflangindex": "27",
      "c_isExcludeTranslate": false,
      "c_isMobileOnlyInMobileNav": false,
      "c_showGender": false,
      "c_showInMenu": false,
      "c_showInSidebarMenu": false,
      "c_siteSiteMapRemove": false
          },
    {
      "_type": "category",
      "categories": [
        {
          "_type": "category",
          "id": "mens-hupana",
          "name": "Hupana",
          "parent_category_id": "hupana"
                  },
        {
          "_type": "category",
          "id": "womens-hupana",
          "name": "Hupana",
          "parent_category_id": "hupana"
                  }
              ],
      "id": "hupana",
      "name": "Hupana",
      "parent_category_id": "root",
      "c_catShowGender": true,
      "c_enableCompare": false,
      "c_hideInDSS": false,
      "c_isMobileOnlyInMobileNav": false,
      "c_pageDisableInfinite": false,
      "c_removeHokaRideFinder": false,
      "c_showGender": true,
      "c_showInEndlessAisleMenu": false,
      "c_showInMenu": false,
      "c_showInSidebarMenu": false,
      "c_siteSiteMapRemove": false
          },
    {
      "_type": "category",
      "id": "instinct",
      "name": "Speed Instinct",
      "parent_category_id": "root"
          },
    {
      "_type": "category",
      "id": "new",
      "name": "launch",
      "parent_category_id": "root",
      "c_catShowGender": false,
      "c_enableCompare": false,
      "c_hreflangindex": "51",
      "c_isExcludeTranslate": false,
      "c_isMobileOnlyInMobileNav": false,
      "c_pageDisableInfinite": false,
      "c_showGender": false,
      "c_showInMenu": false,
      "c_showInSidebarMenu": false,
      "c_siteSiteMapRemove": false
          },
    {
      "_type": "category",
      "description": "Products that are offline that are re-directed to similar category pages",
      "id": "offline",
      "name": "offline",
      "parent_category_id": "root"
          },
    {
      "_type": "category",
      "id": "oiselle-hoka-collab",
      "name": "Oiselle",
      "page_description": "We've joined forces with women's apparel company Oiselle to bring you a special edition Clayton 2 and select apparel from Oiselle's Spring line.",
      "page_title": "HOKA ONE ONE® X Oiselle Collab | Women's Running Apparel and Shoes | Free Shipping",
      "parent_category_id": "root",
      "c_catShowGender": false,
      "c_enableCompare": false,
      "c_hideInDSS": false,
      "c_isExcludeTranslate": false,
      "c_isMobileOnlyInMobileNav": false,
      "c_pageDisableInfinite": false,
      "c_removeHokaRideFinder": false,
      "c_showGender": false,
      "c_showInEndlessAisleMenu": false,
      "c_showInMenu": false,
      "c_showInSidebarMenu": false,
      "c_siteSiteMapRemove": false
          },
    {
      "_type": "category",
      "categories": [
        {
          "_type": "category",
          "description": "The Men's and Women's Constant",
          "id": "The Constant",
          "name": "The Constant",
          "page_description": "The CONSTANT 2 is the most stable shoe in the HOKA ONE ONE® line.",
          "page_title": "HOKA ONE ONE® | The Constant | ",
          "parent_category_id": "related-styles",
          "c_catShowGender": false,
          "c_enableCompare": false,
          "c_isExcludeTranslate": false,
          "c_showGender": false,
          "c_showInMenu": false,
          "c_showInSidebarMenu": false,
          "c_siteSiteMapRemove": false
                  },
        {
          "_type": "category",
          "description": "Unfortunately, we no longer have the Kailua Tarmac available.  Please look at the related products below.",
          "id": "related-styles-kailua-tarmac",
          "name": "the Kailua Tarmac",
          "page_description": "Check out the Kailua Tarmac - featuring an over sized HOKA ONE ONE proprietary midsole. Available in both Men and Women sizes and styles.",
          "page_title": "Hoka One One Kailua Tarmac Related Styles | Official Hoka One One site",
          "parent_category_id": "related-styles",
          "c_catShowGender": false,
          "c_enableCompare": false,
          "c_isExcludeTranslate": false,
          "c_showGender": false,
          "c_showInMenu": false,
          "c_showInSidebarMenu": false,
          "c_siteSiteMapRemove": false
                  },
        {
          "_type": "category",
          "description": "Unfortunately, we no longer have the Mafate 3 available.  Please look at the related products below.",
          "id": "related-styles-mafate-3",
          "name": "the Mafate 3?",
          "page_description": "Check out the Mafate 3 - featuring an over sized HOKA ONE ONE proprietary midsole. Available in both Men and Women sizes and styles.",
          "page_title": "Hoka One One Mafate 3 Related Styles | Official Hoka One One site",
          "parent_category_id": "related-styles",
          "c_catShowGender": false,
          "c_enableCompare": false,
          "c_isExcludeTranslate": false,
          "c_showGender": false,
          "c_showInMenu": false,
          "c_showInSidebarMenu": false,
          "c_siteSiteMapRemove": false
                  },
        {
          "_type": "category",
          "description": "Unfortunately, we no longer have the Rapa Nui available.  Please look at the related products below.",
          "id": "related-styles-rapa-nui",
          "name": "the Rapa Nui",
          "page_description": "Check out the Rapa Nui - featuring an over sized HOKA ONE ONE proprietary midsole. Available in both Men and Women sizes and styles.",
          "page_title": "Hoka One One Rapa Nui Related Styles | Official Hoka One One site",
          "parent_category_id": "related-styles",
          "c_catShowGender": false,
          "c_enableCompare": false,
          "c_isExcludeTranslate": false,
          "c_isMobileOnlyInMobileNav": false,
          "c_showGender": false,
          "c_showInMenu": false,
          "c_showInSidebarMenu": false,
          "c_siteSiteMapRemove": false
                  },
        {
          "_type": "category",
          "description": "Unfortunately, we no longer have the Stinson Tarmac available.  Please look at the related products below.",
          "id": "related-styles-stinson-tarmac",
          "name": "the Stinson Tarmac?",
          "page_description": "Check out the Stinson Tarmac - featuring an over sized HOKA ONE ONE proprietary midsole. Available in both Men and Women sizes and styles.",
          "page_title": "Hoka One One Stinson Tarmac Related Styles | Official Hoka One One site",
          "parent_category_id": "related-styles",
          "c_catShowGender": false,
          "c_enableCompare": false,
          "c_isExcludeTranslate": false,
          "c_showGender": false,
          "c_showInMenu": false,
          "c_showInSidebarMenu": false,
          "c_siteSiteMapRemove": false
                  }
              ],
      "description": "Related Styles category pages",
      "id": "related-styles",
      "name": "Related Styles",
      "page_description": "Looking for a specific shoe? Shop HOKA ONE ONE®? products that are similar to what you're looking for in case we've sold out of a product.",
      "page_title": "HOKA ONE ONE® | Related Styles | Free Shipping & Returns",
      "parent_category_id": "root",
      "c_catShowGender": false,
      "c_enableCompare": false,
      "c_hreflangindex": "28",
      "c_isExcludeTranslate": false,
      "c_isMobileOnlyInMobileNav": false,
      "c_pageDisableInfinite": false,
      "c_showGender": false,
      "c_showInMenu": false,
      "c_showInSidebarMenu": false,
      "c_siteSiteMapRemove": false
          },
    {
      "_type": "category",
      "id": "road",
      "name": "Road",
      "parent_category_id": "root",
      "c_catShowGender": true,
      "c_enableCompare": false,
      "c_hideInDSS": false,
      "c_isMobileOnlyInMobileNav": false,
      "c_pageDisableInfinite": false,
      "c_removeHokaRideFinder": false,
      "c_showGender": true,
      "c_showInEndlessAisleMenu": false,
      "c_showInMenu": false,
      "c_showInSidebarMenu": false,
      "c_siteSiteMapRemove": false
          },
    {
      "_type": "category",
      "id": "running-gear",
      "name": "Running Gear",
      "page_description": "HOKA's newest line of apparel and running gear for men and women has arrived. Shop running bags, tees, weather-proof jackets, and more on HOKAONEONE.com",
      "page_title": "HOKA ONE ONE® | Running Gear for Men and Women | Free Shipping",
      "parent_category_id": "root",
      "c_catShowGender": true,
      "c_enableCompare": false,
      "c_hreflangindex": "25",
      "c_isExcludeTranslate": false,
      "c_isMobileOnlyInMobileNav": false,
      "c_pageDisableInfinite": false,
      "c_removeHokaRideFinder": false,
      "c_showGender": true,
      "c_showInMenu": false,
      "c_showInSidebarMenu": false,
      "c_siteSiteMapRemove": false
          },
    {
      "_type": "category",
      "id": "sale",
      "name": "Sale",
      "page_description": "Shop the official HOKA ONE ONE® Sale and get your favorite, max-cushioned running shoes at a discounted price with free shipping and returns on all orders.",
      "page_title": "HOKA ONE ONE® Sale | Discounted Running Shoes for Men & Women",
      "parent_category_id": "root",
      "c_catShowGender": true,
      "c_enableCompare": false,
      "c_hideInDSS": false,
      "c_hreflangindex": "2",
      "c_isExcludeTranslate": false,
      "c_isMobileOnlyInMobileNav": false,
      "c_pageDisableInfinite": false,
      "c_removeHokaRideFinder": false,
      "c_showGender": false,
      "c_showInEndlessAisleMenu": false,
      "c_showInMenu": true,
      "c_showInSidebarMenu": false,
      "c_siteSiteMapRemove": false
          },
    {
      "_type": "category",
      "description": "duplicate of content asset shop.html",
      "id": "shop",
      "name": "shop",
      "page_description": "Shop the official HOKA ONE ONE® website for max-cushioned running shoes for the road, track, or trails. Free shipping on all online orders.",
      "page_title": "HOKA ONE ONE® | Shop the Official Site",
      "parent_category_id": "root",
      "c_catShowGender": false,
      "c_enableCompare": false,
      "c_hreflangindex": "29",
      "c_isExcludeTranslate": false,
      "c_isMobileOnlyInMobileNav": false,
      "c_showGender": false,
      "c_showInMenu": false,
      "c_showInSidebarMenu": false,
      "c_siteSiteMapRemove": false
          },
    {
      "_type": "category",
      "description": "Using this to add category for A/B tests.",
      "id": "shop-hoka",
      "name": "Shop Hoka",
      "page_description": "Give it a try and shop HOKA ONE ONE®. If for any reason within the first 30 days you are not satisfied, we will exchange or replace your product. No questions!",
      "page_title": "Shop Official HOKA ONE ONE® Running Shoes",
      "parent_category_id": "root",
      "c_catShowGender": false,
      "c_enableCompare": false,
      "c_hreflangindex": "34",
      "c_isExcludeTranslate": false,
      "c_isMobileOnlyInMobileNav": false,
      "c_pageDisableInfinite": false,
      "c_showGender": false,
      "c_showInMenu": false,
      "c_showInSidebarMenu": false,
      "c_siteSiteMapRemove": false
          },
    {
      "_type": "category",
      "id": "speedgoat-2",
      "name": "Speedgoat 2",
      "parent_category_id": "root",
      "c_catShowGender": true,
      "c_enableCompare": false,
      "c_hideInDSS": false,
      "c_isMobileOnlyInMobileNav": false,
      "c_pageDisableInfinite": false,
      "c_removeHokaRideFinder": false,
      "c_showGender": true,
      "c_showInEndlessAisleMenu": false,
      "c_showInMenu": false,
      "c_showInSidebarMenu": false,
      "c_siteSiteMapRemove": false
          },
    {
      "_type": "category",
      "id": "stability-shoes",
      "name": "Stability Shoes",
      "parent_category_id": "root",
      "c_catShowGender": true,
      "c_enableCompare": false,
      "c_hideInDSS": false,
      "c_isMobileOnlyInMobileNav": false,
      "c_pageDisableInfinite": false,
      "c_removeHokaRideFinder": false,
      "c_showGender": true,
      "c_showInEndlessAisleMenu": false,
      "c_showInMenu": false,
      "c_showInSidebarMenu": false,
      "c_siteSiteMapRemove": false
          },
    {
      "_type": "category",
      "id": "stinson-3",
      "name": "Stinson 3",
      "parent_category_id": "root"
          },
    {
      "_type": "category",
      "categories": [
        {
          "_type": "category",
          "id": "bondi-4",
          "name": "Bondi 4",
          "parent_category_id": "top-picks",
          "c_catShowGender": true,
          "c_enableCompare": false,
          "c_hreflangindex": "52",
          "c_isExcludeTranslate": false,
          "c_isMobileOnlyInMobileNav": false,
          "c_pageDisableInfinite": false,
          "c_showGender": true,
          "c_showInMenu": false,
          "c_showInSidebarMenu": false,
          "c_siteSiteMapRemove": false
                  },
        {
          "_type": "category",
          "id": "challenger-atr-2",
          "name": "Challenger ATR 2",
          "page_description": "The HOKA ONE ONE® Challenger ATR 2 is here! It's been updated with a more supportive fit through the midfoot, and increased comfort across the top of the foot",
          "page_title": "HOKA ONE ONE® | Challenger ATR 2 | Free Shipping & Returns",
          "parent_category_id": "top-picks",
          "c_catShowGender": true,
          "c_enableCompare": false,
          "c_hreflangindex": "38",
          "c_isExcludeTranslate": false,
          "c_isMobileOnlyInMobileNav": false,
          "c_pageDisableInfinite": false,
          "c_showGender": true,
          "c_showInMenu": false,
          "c_showInSidebarMenu": false,
          "c_siteSiteMapRemove": false
                  },
        {
          "_type": "category",
          "id": "clayton",
          "name": "Clayton",
          "page_description": "The HOKA ONE ONE® Clayton has revolutionizing lightweight cushioning, featuring PRO2LITE technology with a softer heel for cushioning and a firmer forefoot for propulsion",
          "page_title": "HOKA ONE ONE® | Clayton Road Running Shoe | Free Shipping",
          "parent_category_id": "top-picks",
          "c_catShowGender": true,
          "c_enableCompare": false,
          "c_hreflangindex": "37",
          "c_isExcludeTranslate": false,
          "c_isMobileOnlyInMobileNav": false,
          "c_pageDisableInfinite": false,
          "c_showGender": true,
          "c_showInMenu": false,
          "c_showInSidebarMenu": false,
          "c_siteSiteMapRemove": false
                  },
        {
          "_type": "category",
          "id": "clifton-3",
          "name": "Clifton 3",
          "parent_category_id": "top-picks",
          "c_catShowGender": true,
          "c_enableCompare": false,
          "c_hreflangindex": "43",
          "c_isExcludeTranslate": false,
          "c_isMobileOnlyInMobileNav": false,
          "c_pageDisableInfinite": false,
          "c_showGender": true,
          "c_showInMenu": false,
          "c_showInSidebarMenu": false,
          "c_siteSiteMapRemove": false
                  },
        {
          "_type": "category",
          "id": "clifton3",
          "name": "Clifton 3",
          "parent_category_id": "top-picks",
          "c_catShowGender": false,
          "c_enableCompare": false,
          "c_hreflangindex": "53",
          "c_isExcludeTranslate": false,
          "c_isMobileOnlyInMobileNav": false,
          "c_pageDisableInfinite": false,
          "c_showGender": false,
          "c_showInMenu": false,
          "c_showInSidebarMenu": false,
          "c_siteSiteMapRemove": false
                  },
        {
          "_type": "category",
          "id": "conquest-3",
          "name": "Conquest 3",
          "parent_category_id": "top-picks",
          "c_catShowGender": true,
          "c_enableCompare": false,
          "c_hreflangindex": "54",
          "c_isExcludeTranslate": false,
          "c_isMobileOnlyInMobileNav": false,
          "c_pageDisableInfinite": false,
          "c_showGender": true,
          "c_showInMenu": false,
          "c_showInSidebarMenu": false,
          "c_siteSiteMapRemove": false
                  },
        {
          "_type": "category",
          "id": "constant-2",
          "name": "Constant 2",
          "parent_category_id": "top-picks",
          "c_catShowGender": false,
          "c_enableCompare": false,
          "c_hreflangindex": "55",
          "c_isExcludeTranslate": false,
          "c_isMobileOnlyInMobileNav": false,
          "c_pageDisableInfinite": false,
          "c_showGender": false,
          "c_showInMenu": false,
          "c_showInSidebarMenu": false,
          "c_siteSiteMapRemove": false
                  },
        {
          "_type": "category",
          "id": "infinite",
          "name": "Infinite",
          "page_description": "The same experience of lightweight cushioning found in the Clifton 2 is now available for runners seeking a medium level of support in the INFINITE",
          "page_title": "HOKA ONE ONE® | Infinite Road Running Shoe | Free Shipping",
          "parent_category_id": "top-picks",
          "c_catShowGender": true,
          "c_enableCompare": false,
          "c_hreflangindex": "56",
          "c_isExcludeTranslate": false,
          "c_isMobileOnlyInMobileNav": false,
          "c_pageDisableInfinite": false,
          "c_showGender": true,
          "c_showInMenu": false,
          "c_showInSidebarMenu": false,
          "c_siteSiteMapRemove": false
                  },
        {
          "_type": "category",
          "id": "kona-collection",
          "name": "Kona Collection",
          "page_description": "Get ready for race day with the tried and true Clayton, reimagined in a tropical print inspired by the island. Get free Shipping and Returns on all HOKAONEONE.com orders!",
          "page_title": "HOKA ONE ONE® | The KONA Clayton for Men and Women | Road Running Shoe",
          "parent_category_id": "top-picks",
          "c_catShowGender": true,
          "c_enableCompare": false,
          "c_hreflangindex": "57",
          "c_isExcludeTranslate": false,
          "c_isMobileOnlyInMobileNav": false,
          "c_pageDisableInfinite": false,
          "c_showGender": true,
          "c_showInMenu": false,
          "c_showInSidebarMenu": false,
          "c_siteSiteMapRemove": false
                  },
        {
          "_type": "category",
          "id": "ora-slides",
          "name": "Ora Slides",
          "parent_category_id": "top-picks"
                  },
        {
          "_type": "category",
          "id": "speed-instinct",
          "name": "Speed Instinct",
          "parent_category_id": "top-picks",
          "c_catShowGender": true,
          "c_enableCompare": false,
          "c_hreflangindex": "58",
          "c_isExcludeTranslate": false,
          "c_isMobileOnlyInMobileNav": false,
          "c_pageDisableInfinite": false,
          "c_showGender": true,
          "c_showInMenu": false,
          "c_showInSidebarMenu": false,
          "c_siteSiteMapRemove": false
                  },
        {
          "_type": "category",
          "id": "speedgoat",
          "name": "Speedgoat",
          "parent_category_id": "top-picks",
          "c_catShowGender": true,
          "c_enableCompare": false,
          "c_hreflangindex": "40",
          "c_isExcludeTranslate": false,
          "c_isMobileOnlyInMobileNav": false,
          "c_pageDisableInfinite": false,
          "c_showGender": true,
          "c_showInMenu": false,
          "c_showInSidebarMenu": false,
          "c_siteSiteMapRemove": false
                  },
        {
          "_type": "category",
          "id": "tor-tech",
          "name": "Tor Tech",
          "parent_category_id": "top-picks",
          "c_catShowGender": false,
          "c_enableCompare": false,
          "c_hreflangindex": "59",
          "c_isExcludeTranslate": false,
          "c_isMobileOnlyInMobileNav": false,
          "c_pageDisableInfinite": false,
          "c_showGender": false,
          "c_showInMenu": false,
          "c_showInSidebarMenu": false,
          "c_siteSiteMapRemove": false
                  },
        {
          "_type": "category",
          "id": "tracer",
          "name": "Tracer",
          "page_description": "The Tracer’s ultra-lightweight upper reduces water retention to keep the shoe light no matter the conditions.",
          "page_title": "HOKA ONE ONE® | Tracer Road Running Shoe | Free Shipping",
          "parent_category_id": "top-picks",
          "c_catShowGender": true,
          "c_enableCompare": false,
          "c_hreflangindex": "36",
          "c_isExcludeTranslate": false,
          "c_isMobileOnlyInMobileNav": false,
          "c_pageDisableInfinite": false,
          "c_showGender": true,
          "c_showInMenu": false,
          "c_showInSidebarMenu": false,
          "c_siteSiteMapRemove": false
                  },
        {
          "_type": "category",
          "id": "vanquish-2",
          "name": "Vanquish 2",
          "page_description": "The HOKA ONE ONE® Vanquish 2 is a super cushioned and versatile shoe for the runner looking for a springy, responsive ride.",
          "page_title": "HOKA ONE ONE® | Vanquish 2 Road Running Shoe | Free Shipping",
          "parent_category_id": "top-picks",
          "c_catShowGender": true,
          "c_enableCompare": false,
          "c_hreflangindex": "30",
          "c_isExcludeTranslate": false,
          "c_isMobileOnlyInMobileNav": false,
          "c_pageDisableInfinite": false,
          "c_showGender": true,
          "c_showInMenu": false,
          "c_showInSidebarMenu": false,
          "c_siteSiteMapRemove": false
                  },
        {
          "_type": "category",
          "id": "vanquish3",
          "name": "Vanquish 3",
          "parent_category_id": "top-picks"
                  }
              ],
      "id": "top-picks",
      "name": "Top Picks",
      "page_description": "Picking favorites is hard - let HOKA ONE ONE®? do it for you! Shop customer favorites and see which running shoes are covering the most miles.",
      "page_title": "HOKA ONE ONE® | Top Picks | Road, Trail, and Track Running Shoes",
      "parent_category_id": "root",
      "c_catShowGender": true,
      "c_enableCompare": false,
      "c_hreflangindex": "35",
      "c_isExcludeTranslate": false,
      "c_isMobileOnlyInMobileNav": false,
      "c_pageDisableInfinite": false,
      "c_showGender": true,
      "c_showInMenu": false,
      "c_showInSidebarMenu": false,
      "c_siteSiteMapRemove": false
          },
    {
      "_type": "category",
      "id": "tor-footwear",
      "name": "Tor Footwear",
      "parent_category_id": "root",
      "c_catShowGender": true,
      "c_enableCompare": false,
      "c_isExcludeTranslate": false,
      "c_isMobileOnlyInMobileNav": false,
      "c_pageDisableInfinite": false,
      "c_removeHokaRideFinder": false,
      "c_showGender": true,
      "c_showInMenu": false,
      "c_showInSidebarMenu": false,
      "c_siteSiteMapRemove": false
          },
    {
      "_type": "category",
      "description": "non gendered trail page",
      "id": "trail",
      "name": "Trail",
      "parent_category_id": "root",
      "c_catShowGender": true,
      "c_enableCompare": false,
      "c_hideInDSS": false,
      "c_isMobileOnlyInMobileNav": false,
      "c_pageDisableInfinite": false,
      "c_removeHokaRideFinder": false,
      "c_showGender": true,
      "c_showInEndlessAisleMenu": false,
      "c_showInMenu": false,
      "c_showInSidebarMenu": false,
      "c_siteSiteMapRemove": false
          },
    {
      "_type": "category",
      "id": "walking-shoes",
      "name": "walking shoes",
      "parent_category_id": "root",
      "c_catShowGender": true,
      "c_enableCompare": false,
      "c_hideInDSS": false,
      "c_isMobileOnlyInMobileNav": false,
      "c_pageDisableInfinite": false,
      "c_removeHokaRideFinder": false,
      "c_showGender": true,
      "c_showInEndlessAisleMenu": false,
      "c_showInMenu": false,
      "c_showInSidebarMenu": false,
      "c_siteSiteMapRemove": false
          },
    {
      "_type": "category",
      "id": "gear",
      "name": "Gear",
      "page_description": "Find all the HOKA ONE ONE® Men's and Women's Running Gear you need, including breathable tech tees. Get them just in time for training outdoors.",
      "page_title": "Men's & Women's Running Gear | HOKA ONE ONE® Official Site",
      "parent_category_id": "root",
      "c_catShowGender": false,
      "c_enableCompare": false,
      "c_hreflangindex": "25",
      "c_isExcludeTranslate": false,
      "c_isMobileOnlyInMobileNav": false,
      "c_pageDisableInfinite": false,
      "c_showGender": false,
      "c_showInMenu": false,
      "c_showInSidebarMenu": false,
      "c_siteSiteMapRemove": false
          },
    {
      "_type": "category",
      "id": "new-arrivals",
      "name": "New Arrivals",
      "page_description": "The Arahi stability road running shoe by HOKA ONE ONE® is here! There's another new shoe on the block, too - the Hupana! Get free shipping on all orders.",
      "page_title": "HOKA ONE ONE® | New Running Shoes Arrivals | Free Shipping & Returns",
      "parent_category_id": "root",
      "c_catShowGender": true,
      "c_enableCompare": false,
      "c_hideInDSS": false,
      "c_hreflangindex": "1",
      "c_isExcludeTranslate": false,
      "c_isMobileOnlyInMobileNav": false,
      "c_pageDisableInfinite": false,
      "c_removeHokaRideFinder": false,
      "c_showGender": true,
      "c_showInEndlessAisleMenu": false,
      "c_showInMenu": true,
      "c_showInSidebarMenu": false,
      "c_siteSiteMapRemove": false
          },
    {
      "_type": "category",
      "categories": [
        {
          "_type": "category",
          "id": "mens-apparel-gear",
          "name": "Apparel/Gear",
          "parent_category_id": "men"
                  },
        {
          "_type": "category",
          "id": "mens-recovery-sandals",
          "name": "Recovery Sandals",
          "page_description": "HOKA ONE ONE® Men's Recovery Sandals are designed for post-runs, post-hikes, or just an easy slip-on-and-go sandal. Get free shipping on all orders.",
          "page_title": "HOKA ONE ONE® | Men's Recovery Sandals | Free Shipping",
          "parent_category_id": "men",
          "c_alternativeUrl": "https://dw25-web-deckers.demandware.net/on/demandware.store/Sites-HOKA-US-Site/default/Product-Show?pid=1014864",
          "c_catShowGender": false,
          "c_enableCompare": false,
          "c_hideInDSS": false,
          "c_isExcludeTranslate": false,
          "c_isMobileOnlyInMobileNav": false,
          "c_pageDisableInfinite": false,
          "c_removeHokaRideFinder": false,
          "c_showGender": false,
          "c_showInEndlessAisleMenu": false,
          "c_showInMenu": true,
          "c_showInSidebarMenu": false,
          "c_siteSiteMapRemove": false
                  },
        {
          "_type": "category",
          "id": "mens-shoes",
          "name": "Shoes",
          "parent_category_id": "men"
                  },
        {
          "_type": "category",
          "id": "mens-bestsellers",
          "name": "Best Sellers",
          "page_description": "HOKA ONE ONE® Men's Performance Running, Hiking, & Walking shoes. Check out the top selling pairs of HOKA ONE ONE shoes! Try any pair for 30 days.",
          "page_title": "HOKA ONE ONE® | Men's Best Selling Running Shoes",
          "parent_category_id": "men",
          "c_catShowGender": false,
          "c_enableCompare": false,
          "c_hideInDSS": false,
          "c_isExcludeTranslate": false,
          "c_isMobileOnlyInMobileNav": false,
          "c_pageDisableInfinite": false,
          "c_removeHokaRideFinder": false,
          "c_showGender": false,
          "c_showInEndlessAisleMenu": false,
          "c_showInMenu": true,
          "c_showInSidebarMenu": false,
          "c_siteSiteMapRemove": false
                  },
        {
          "_type": "category",
          "id": "mens-road",
          "name": "Road",
          "page_description": "Explore new roads with HOKA ONE ONE® Men's Road Running Shoes for maximum cushioning with minimal weight. Free shipping & returns.",
          "page_title": "HOKA ONE ONE® | Men's Road Running Shoes | Time to fly™",
          "parent_category_id": "men",
          "c_catShowGender": false,
          "c_enableCompare": false,
          "c_hideInDSS": false,
          "c_hreflangindex": "6",
          "c_isExcludeTranslate": false,
          "c_isMobileOnlyInMobileNav": false,
          "c_pageDisableInfinite": false,
          "c_removeHokaRideFinder": false,
          "c_showGender": false,
          "c_showInEndlessAisleMenu": false,
          "c_showInMenu": true,
          "c_showInSidebarMenu": false,
          "c_siteSiteMapRemove": false
                  },
        {
          "_type": "category",
          "id": "mens-trail",
          "name": "Trail",
          "page_description": "HOKA ONE ONE® Men's Trail Running Shoes are perfect for exploring new terrain with maximum cushioning and minimal weight. Try it for 30 days.",
          "page_title": "HOKA ONE ONE® | Men's Trail Running Shoes | Time to fly™",
          "parent_category_id": "men",
          "c_catShowGender": false,
          "c_enableCompare": false,
          "c_hideInDSS": false,
          "c_hreflangindex": "7",
          "c_isExcludeTranslate": false,
          "c_isMobileOnlyInMobileNav": false,
          "c_pageDisableInfinite": false,
          "c_removeHokaRideFinder": false,
          "c_showGender": false,
          "c_showInEndlessAisleMenu": false,
          "c_showInMenu": true,
          "c_showInSidebarMenu": false,
          "c_siteSiteMapRemove": false
                  },
        {
          "_type": "category",
          "description": "Experience the comfort, durability, and advanced technology of HOKA ONE ONE running shoes in our new line of Hiking Boots and Shoes for Men.",
          "id": "men-hiking",
          "name": "Hiking",
          "page_description": "Check out the new HOKA ONE ONE® Men's Max Cushioned Hiking Shoes and Boots. Hike the trails all day with these waterproof and lightweight shoes.",
          "page_title": "HOKA ONE ONE® | Men's Max Cushioned Hiking Shoes and Boots",
          "parent_category_id": "men",
          "c_catShowGender": false,
          "c_enableCompare": false,
          "c_hideInDSS": false,
          "c_hreflangindex": "8",
          "c_isExcludeTranslate": false,
          "c_isMobileOnlyInMobileNav": false,
          "c_pageDisableInfinite": false,
          "c_removeHokaRideFinder": false,
          "c_showGender": false,
          "c_showInEndlessAisleMenu": false,
          "c_showInMenu": true,
          "c_showInSidebarMenu": false,
          "c_siteSiteMapRemove": false
                  },
        {
          "_type": "category",
          "id": "mens-view-all",
          "name": "View All",
          "page_description": "View all HOKA ONE ONE® Men's Running and Hiking Shoes - perfect for the trail with maximum cushioning and excellent traction. Free shipping & returns.",
          "page_title": "HOKA ONE ONE® | Men's Running & Hiking Shoes | Time to fly™",
          "parent_category_id": "men",
          "c_catShowGender": false,
          "c_enableCompare": false,
          "c_hideInDSS": false,
          "c_hreflangindex": "23",
          "c_isExcludeTranslate": false,
          "c_isMobileOnlyInMobileNav": false,
          "c_pageDisableInfinite": false,
          "c_removeHokaRideFinder": true,
          "c_showGender": false,
          "c_showInEndlessAisleMenu": false,
          "c_showInMenu": false,
          "c_showInSidebarMenu": false,
          "c_siteSiteMapRemove": false
                  },
        {
          "_type": "category",
          "id": "mens-track",
          "name": "Competition",
          "page_description": "HOKA ONE ONE® Men's Track Running Shoes are lightweight, responsive and flexible. These track running shoes are designed to make you fly.",
          "page_title": "HOKA ONE ONE® | Men's Track Running Shoes | Time to fly™",
          "parent_category_id": "men",
          "c_catShowGender": true,
          "c_enableCompare": false,
          "c_isExcludeTranslate": false,
          "c_isMobileOnlyInMobileNav": false,
          "c_pageDisableInfinite": false,
          "c_removeHokaRideFinder": true,
          "c_showGender": true,
          "c_showInMenu": false,
          "c_showInSidebarMenu": false,
          "c_siteSiteMapRemove": false
                  },
        {
          "_type": "category",
          "id": "mens-wides",
          "name": "Wides",
          "parent_category_id": "men",
          "c_catShowGender": false,
          "c_enableCompare": false,
          "c_hideInDSS": false,
          "c_isMobileOnlyInMobileNav": false,
          "c_pageDisableInfinite": false,
          "c_removeHokaRideFinder": false,
          "c_showGender": false,
          "c_showInEndlessAisleMenu": false,
          "c_showInMenu": false,
          "c_showInSidebarMenu": false,
          "c_siteSiteMapRemove": false
                  },
        {
          "_type": "category",
          "id": "mens-gear",
          "name": "Apparel",
          "page_description": "Shop HOKA ONE ONE® for men's runner bags, jackets, and technical tees so you're able to run in style from head to toe. Get free shipping on all HOKA orders!",
          "page_title": "HOKA ONE ONE® | Men's Running Gear | Bags, Tees, and More",
          "parent_category_id": "men",
          "c_catShowGender": true,
          "c_enableCompare": false,
          "c_hideInDSS": false,
          "c_hreflangindex": "9",
          "c_isExcludeTranslate": false,
          "c_isMobileOnlyInMobileNav": false,
          "c_pageDisableInfinite": false,
          "c_removeHokaRideFinder": true,
          "c_showGender": true,
          "c_showInEndlessAisleMenu": false,
          "c_showInMenu": true,
          "c_showInSidebarMenu": false,
          "c_siteSiteMapRemove": false
                  }
              ],
      "id": "men",
      "name": "Men",
      "page_description": "Shop HOKA ONE ONE® Men's Running and Hiking Shoes - perfect for the trail with maximum cushioning and excellent traction. Free shipping & returns.",
      "page_title": "HOKA ONE ONE® | Men's Running & Hiking Shoes | Time to fly™",
      "parent_category_id": "root",
      "thumbnail": "https://dw25-web-deckers.demandware.net/on/demandware.static/-/Sites-siteCatalogHoka-US/default/v1514346396403/app/mens_hoka_360.png",
      "c_alternativeUrl": "https://dw25-web-deckers.demandware.net/s/HOKA-US/mens-view-all/",
      "c_catShowGender": false,
      "c_enableCompare": false,
      "c_hideInDSS": false,
      "c_hreflangindex": "5",
      "c_isExcludeTranslate": false,
      "c_isMobileOnlyInMobileNav": false,
      "c_pageDisableInfinite": false,
      "c_removeHokaRideFinder": false,
      "c_showGender": false,
      "c_showInEndlessAisleMenu": true,
      "c_showInMenu": true,
      "c_showInSidebarMenu": false,
      "c_siteSiteMapRemove": false,
      "c_sizeChartID": "size-fit-men-shoes"
          },
    {
      "_type": "category",
      "categories": [
        {
          "_type": "category",
          "id": "womens-apparel-gear",
          "name": "Apparel/Gear",
          "parent_category_id": "women"
                  },
        {
          "_type": "category",
          "id": "womens-recovery-sandals",
          "name": "Recovery Sandals",
          "page_description": "HOKA ONE ONE® Women's Recovery Sandals are designed for post-runs, post-hikes, or just an easy slip-on-and-go sandal. Get free shipping on all orders.",
          "page_title": "HOKA ONE ONE® | Women's Recovery Sandals | Free Shipping",
          "parent_category_id": "women",
          "c_alternativeUrl": "https://dw25-web-deckers.demandware.net/on/demandware.store/Sites-HOKA-US-Site/default/Product-Show?pid=1014865",
          "c_catShowGender": false,
          "c_enableCompare": false,
          "c_hideInDSS": false,
          "c_isExcludeTranslate": false,
          "c_isMobileOnlyInMobileNav": false,
          "c_pageDisableInfinite": false,
          "c_removeHokaRideFinder": false,
          "c_showGender": false,
          "c_showInEndlessAisleMenu": false,
          "c_showInMenu": true,
          "c_showInSidebarMenu": false,
          "c_siteSiteMapRemove": false
                  },
        {
          "_type": "category",
          "id": "womens-track",
          "name": "Competition",
          "page_description": "HOKA ONE ONE® Women's Track Running Shoes are lightweight, responsive and flexible. These track running shoes are designed to make you fly.",
          "page_title": "HOKA ONE ONE® | Women's Track Running Shoes | Time to fly™",
          "parent_category_id": "women",
          "c_catShowGender": true,
          "c_enableCompare": false,
          "c_isExcludeTranslate": false,
          "c_isMobileOnlyInMobileNav": false,
          "c_pageDisableInfinite": false,
          "c_showGender": true,
          "c_showInMenu": false,
          "c_showInSidebarMenu": false,
          "c_siteSiteMapRemove": false
                  },
        {
          "_type": "category",
          "id": "womens-bestsellers",
          "name": "Best Sellers",
          "page_description": "Shop women's HOKA ONE ONE®'s best selling running shoes complete with maximum cushioning and excellent traction. Free shipping and returns!",
          "page_title": "HOKA ONE ONE® | Women's Best Selling Running Shoes",
          "parent_category_id": "women",
          "c_catShowGender": false,
          "c_enableCompare": false,
          "c_hideInDSS": false,
          "c_isExcludeTranslate": false,
          "c_isMobileOnlyInMobileNav": false,
          "c_pageDisableInfinite": false,
          "c_removeHokaRideFinder": false,
          "c_showGender": false,
          "c_showInEndlessAisleMenu": false,
          "c_showInMenu": true,
          "c_showInSidebarMenu": false,
          "c_siteSiteMapRemove": false
        }, {
          "_type": "category",
          "id": "womens-road",
          "name": "Road",
          "page_description": "Explore new roads with HOKA ONE ONE® Women's Road Running Shoes. Experience maximum cushioning with minimal weight. Free shipping & returns.",
          "page_title": "HOKA ONE ONE® | Women's Road Running Shoes | Time to fly™",
          "parent_category_id": "women",
          "c_catShowGender": false,
          "c_enableCompare": false,
          "c_hideInDSS": false,
          "c_hreflangindex": "11",
          "c_isExcludeTranslate": false,
          "c_isMobileOnlyInMobileNav": false,
          "c_pageDisableInfinite": false,
          "c_removeHokaRideFinder": false,
          "c_showGender": false,
          "c_showInEndlessAisleMenu": false,
          "c_showInMenu": true,
          "c_showInSidebarMenu": false,
          "c_siteSiteMapRemove": false
                  },
        {
          "_type": "category",
          "id": "womens-trail",
          "name": "Trail",
          "page_description": "HOKA ONE ONE® Women's Trail Running Shoes are perfect for exploring new terrain with maximum cushioning and minimal weight. Try it for 30 days.",
          "page_title": "HOKA ONE ONE® | Women's Trail Running Shoes | Time to fly™",
          "parent_category_id": "women",
          "c_catShowGender": false,
          "c_enableCompare": false,
          "c_hideInDSS": false,
          "c_hreflangindex": "12",
          "c_isExcludeTranslate": false,
          "c_isMobileOnlyInMobileNav": false,
          "c_pageDisableInfinite": false,
          "c_removeHokaRideFinder": false,
          "c_showGender": false,
          "c_showInEndlessAisleMenu": false,
          "c_showInMenu": true,
          "c_showInSidebarMenu": false,
          "c_siteSiteMapRemove": false
        }, {
          "_type": "category",
          "description": "Experience the comfort, durability, and advanced technology of HOKA ONE ONE running shoes in our new line of Hiking Boots and Shoes for Women.",
          "id": "women-hiking",
          "name": "Hiking",
          "page_description": "Check out the new HOKA ONE ONE® Women's Max Cushioned Hiking Shoes and Boots. Hike the trails all day with these waterproof and lightweight shoes.",
          "page_title": "HOKA ONE ONE® | Women's Max Cushioned Hiking Shoes and Boots",
          "parent_category_id": "women",
          "c_catShowGender": false,
          "c_enableCompare": false,
          "c_hideInDSS": false,
          "c_hreflangindex": "13",
          "c_isExcludeTranslate": false,
          "c_isMobileOnlyInMobileNav": false,
          "c_pageDisableInfinite": false,
          "c_removeHokaRideFinder": false,
          "c_showGender": false,
          "c_showInEndlessAisleMenu": false,
          "c_showInMenu": true,
          "c_showInSidebarMenu": false,
          "c_siteSiteMapRemove": false
        }, {
          "_type": "category",
          "id": "womens-gear",
          "name": "Apparel",
          "page_description": "Shop HOKA ONE ONE® for women's runner bags, jackets, and technical tees so you're able to run in style from head to toe. Get free shipping on all HOKA orders!",
          "page_title": "HOKA ONE ONE® | Women's Running Gear | Bags, Tees, and More",
          "parent_category_id": "women",
          "c_catShowGender": true,
          "c_enableCompare": false,
          "c_hreflangindex": "14",
          "c_isExcludeTranslate": false,
          "c_isMobileOnlyInMobileNav": false,
          "c_pageDisableInfinite": false,
          "c_removeHokaRideFinder": true,
          "c_showGender": true,
          "c_showInMenu": true,
          "c_showInSidebarMenu": false,
          "c_siteSiteMapRemove": false
        }, {
          "_type": "category",
          "id": "womens-view-all",
          "name": "View All",
          "page_description": "Shop HOKA ONE ONE® Women's Running & Hiking Shoes with maximum cushioning and excellent traction. Find women's running & hiking shoes today.",
          "page_title": "HOKA ONE ONE® | Women's Running & Hiking Shoes | Time to fly™",
          "parent_category_id": "women",
          "c_catShowGender": false,
          "c_enableCompare": false,
          "c_hideInDSS": false,
          "c_hreflangindex": "24",
          "c_isExcludeTranslate": false,
          "c_isMobileOnlyInMobileNav": false,
          "c_pageDisableInfinite": false,
          "c_removeHokaRideFinder": true,
          "c_showGender": false,
          "c_showInEndlessAisleMenu": false,
          "c_showInMenu": false,
          "c_showInSidebarMenu": false,
          "c_siteSiteMapRemove": false
        }
      ],
      "id": "women",
      "name": "Women",
      "page_description": "Check out HOKA ONE ONE® Women's Running & Hiking Shoes with maximum cushioning and excellent traction. Shop women's running & hiking shoes today.",
      "page_title": "HOKA ONE ONE® | Women's Running & Hiking Shoes | Time to fly™",
      "parent_category_id": "root",
      "thumbnail": "https://dw25-web-deckers.demandware.net/on/demandware.static/-/Sites-siteCatalogHoka-US/default/v1514346396403/app/womens_hoka_360.png",
      "c_alternativeUrl": "https://dw25-web-deckers.demandware.net/s/HOKA-US/womens-view-all/",
      "c_catShowGender": false,
      "c_enableCompare": false,
      "c_hideInDSS": false,
      "c_hreflangindex": "10",
      "c_isExcludeTranslate": false,
      "c_isMobileOnlyInMobileNav": false,
      "c_pageDisableInfinite": false,
      "c_removeHokaRideFinder": false,
      "c_showGender": false,
      "c_showInEndlessAisleMenu": true,
      "c_showInMenu": true,
      "c_showInSidebarMenu": false,
      "c_siteSiteMapRemove": false,
      "c_sizeChartID": "size-fit-women-shoes"
    }, {
      "_type": "category",
      "id": "best-sellers",
      "name": "Best Sellers",
      "page_description": "HOKA ONE ONE® Performance Running, Hiking, & Walking shoes for men and women. Check out the top selling pairs of HOKA ONE ONE® shoes! Try any pair for 30 days.",
      "page_title": "HOKA ONE ONE® | Best Selling HOKA ONE ONE® Running Shoes",
      "parent_category_id": "root",
      "c_catShowGender": true,
      "c_enableCompare": false,
      "c_hideInDSS": false,
      "c_hreflangindex": "50",
      "c_isExcludeTranslate": false,
      "c_isMobileOnlyInMobileNav": false,
      "c_pageDisableInfinite": false,
      "c_removeHokaRideFinder": false,
      "c_showGender": true,
      "c_showInEndlessAisleMenu": false,
      "c_showInMenu": false,
      "c_showInSidebarMenu": false,
      "c_siteSiteMapRemove": false
    }, {
      "_type": "category",
      "id": "wide",
      "name": "Wides",
      "page_description": "HOKA ONE ONE® now offers Wide sizes for men and women in various selections of running shoes. Don't love the shoes? Try them for 30 days, no questions asked.",
      "page_title": "HOKA ONE ONE® | Wide Size Running Shoes for Men and Women",
      "parent_category_id": "root",
      "c_catShowGender": true,
      "c_enableCompare": false,
      "c_hideInDSS": false,
      "c_hreflangindex": "61",
      "c_isExcludeTranslate": false,
      "c_isMobileOnlyInMobileNav": false,
      "c_pageDisableInfinite": false,
      "c_removeHokaRideFinder": false,
      "c_showGender": true,
      "c_showInEndlessAisleMenu": false,
      "c_showInMenu": true,
      "c_showInSidebarMenu": false,
      "c_siteSiteMapRemove": false
    }],
  "id": "root",
  "name": "Hoka US Site Catalog",
  "page_description": "Each HOKA ONE ONE® running shoe is built upon a maximally cushioned midsole that offers superior protection, comfort and propulsion.",
  "page_title": "HOKA ONE ONE® | Men’s & Women's Max Cushioned Running Shoes",
  "c_catShowGender": false,
  "c_enableCompare": false,
  "c_isExcludeTranslate": false,
  "c_isMobileOnlyInMobileNav": false,
  "c_pageDisableInfinite": false,
  "c_showGender": false,
  "c_showInMenu": false,
  "c_showInSidebarMenu": false,
  "c_siteSiteMapRemove": false
}
